/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */package Utiles.ClasesUtiles.Admininistrador;

import static Utiles.MetodosUtiles.Archivo.arreglarDireccion;
import static Utiles.MetodosUtiles.Visual.buscador;
import static Utiles.MetodosUtiles.Visual.responerException;
import static Utiles.MetodosUtiles.Visual.seguridadJTextField;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Rene
 */
public class Ventana_Cambiar_Direccion extends javax.swing.JFrame implements Runnable {

    private Admininistrador_De_Guardado A;
    private JFileChooser jf = new JFileChooser();
    private final String direccionAnterior, nombreDireccion, direccionAdministrador;
//    private final int PIN;
    private JFrame ventanaAnterior;
    // private Object comunicacion;

    /**
     * Creates new form Ventana_Canviar_Direccion
     */
    public Ventana_Cambiar_Direccion(String direccionAnterior, String nombreDireccion,  Admininistrador_De_Guardado A,String direccionAdministrador,JFrame ventanaAnterior) {
        initComponents();
        this.direccionAnterior = direccionAnterior;
        // this.comunicacion = comunicacion;
        this.A = A;
        this.nombreDireccion = nombreDireccion;
        this.direccionAdministrador=direccionAdministrador;
        this.ventanaAnterior=ventanaAnterior;
//        this.PIN = PIN;
        setLocationRelativeTo(null);
        actualizarT(direccionAnterior);
//        todasLasVentanas[5]=this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        T = new javax.swing.JTextField();
        BCancelar = new javax.swing.JButton();
        BBuscarDireccion = new javax.swing.JButton();
        BAceptar = new javax.swing.JButton();
        LNuevaDireccion = new javax.swing.JLabel();
        BRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Direccion");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltoTeclado(evt);
            }
        });
        PTodo.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, -1));

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PTodo.add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        BBuscarDireccion.setText("Buscar Direccion");
        BBuscarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarDireccionActionPerformed(evt);
            }
        });
        PTodo.add(BBuscarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, -1));

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        PTodo.add(BAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 70, 90, -1));

        LNuevaDireccion.setText("Nueva Direccion");
        PTodo.add(LNuevaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        BRestaurar.setText("Restaurar");
        BRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRestaurarActionPerformed(evt);
            }
        });
        PTodo.add(BRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 70, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        cerrar();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BBuscarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarDireccionActionPerformed
        if (buscador(jf, this)) {
            actualizarT(jf.getSelectedFile() + "");
        }
    }//GEN-LAST:event_BBuscarDireccionActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        if (seguridad()) {
            aceptar();
        }
    }//GEN-LAST:event_TActionPerformed

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_BAceptarActionPerformed

    private void SoltoTeclado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoltoTeclado
        seguridad();
    }//GEN-LAST:event_SoltoTeclado

    private void BRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRestaurarActionPerformed
        actualizarT(direccionAnterior);
    }//GEN-LAST:event_BRestaurarActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
        cerrar();
    }//GEN-LAST:event_cerroVentana

    private boolean seguridad() {
        if (seguridadJTextField(T, obtenerTexto(), BAceptar)) {
            File porDefecto = obtenerFile();
            if (porDefecto.exists()) {
                jf.setSelectedFile(porDefecto);
                return true;
            }
        }
        return false;
    }

    private void actualizarT(String texto) {
        T.setText(texto);
        seguridad();
    }

    public File obtenerFile() {
        return new File(obtenerTexto());
    }

    public String obtenerTexto() {
        return arreglarDireccion(T.getText().trim());
    }

    public synchronized void cerrar() {
        setVisible(false);
        ventanaAnterior.setVisible(true);
        notifyAll();
    }

    public void aceptar() {
        try {

            A.canviarInformacion(nombreDireccion, new File(obtenerTexto()));
            A.guardarAdminastrador(direccionAdministrador);
        } catch (Exception ex) {
            responerException(ex);
        }
//        comunicacion = T.getText();
    }
  //  /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Cambiar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Cambiar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Cambiar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Cambiar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana_Cambiar_Direccion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BBuscarDireccion;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BRestaurar;
    private javax.swing.JLabel LNuevaDireccion;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField T;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        setVisible(true);
    }
}
