/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utiles.ClasesUtiles.Admininistrador;

import Utiles.ClasesUtiles.Interfases.Accion_Cargar_Cancelar;
import Utiles.ClasesUtiles.Admininistrador.Admininistrador_De_Guardado;
import Utiles.MetodosUtiles.Archivo;
import static Utiles.MetodosUtiles.Archivo.crearArchivo;
import java.io.IOException;
import static Utiles.MetodosUtiles.Visual.*;
import java.io.File;
import java.util.Arrays;
//import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Version 0.8
 *
 * @author Rene
 */
public class Ventana_Administrador<E> extends javax.swing.JFrame {
    
    private Admininistrador_De_Guardado<E> A;
    private String direccionAdministrador;
    private JFileChooser jf;
    private Accion_Cargar_Cancelar ac;
    public static final String EXTENCION = ".dir";
    private E instancia;
    private Ventana_Cambiar_Direccion ventana_Canviar_Direccion;

    /**
     * Creates new form Ventana_Administrador_Configuraciones
     */
    public Ventana_Administrador(String direccionAdministrador, Accion_Cargar_Cancelar ac) throws IOException, ClassNotFoundException {
        jf = new JFileChooser();
        jf.setFileFilter(new FileNameExtensionFilter(EXTENCION, EXTENCION.substring(1)));
        this.direccionAdministrador = direccionAdministrador;
        actualizarDatos();
        initComponents();
        actualizarLista();
        setLocationRelativeTo(null);
        selecionarPrimero();
        this.ac = ac;
        seguridad();
        
    }
    
    public Accion_Cargar_Cancelar getAc() {
        return ac;
    }
    
    public void selecionarPrimero() {
        if (L.getComponentCount() != 0) {
            L.setSelectedIndex(0);
        }
    }
    
    public void actualizar() throws IOException, ClassNotFoundException {
        actualizarDatos();
        actualizarLista();
    }
    
    public void actualizarDatos() throws IOException, ClassNotFoundException {
        A = new Admininistrador_De_Guardado(direccionAdministrador);
    }
    
    public void actualizarLista() {
        String a[] = A.getNombres();
        Arrays.sort(a);
        L.setListData(a);
    }
    
    private void seguridad() {
        seguridadJList(L, BCambiarInformacion, BCambiarNombre, BCargar, BEliminar);
        activarJComponent(instancia instanceof File && BCambiarInformacion.isEnabled(), BCambiarInformacion);
        actualizarVistaPrevia();
    }
    
    public String getNombreSelecionado() {
        return (String) L.getSelectedValue();
    }
    
    public E getInformacionSelecionada() {
        return A.getInformacion(getNombreSelecionado());
    }
    
    public void setDireccionAdministrador(String direccionAdministrador) {
        this.direccionAdministrador = direccionAdministrador;
    }
    
    public void actualizarVistaPrevia() {
        if (L.getSelectedIndex() != -1) {
            String a = "";
            Object o = A.getInformacion((String) L.getSelectedValue());
            if (o instanceof java.lang.Iterable) {
                for (Object oc : (java.lang.Iterable) o) {
                    a += oc.toString() + "\n";
                }
            } else {
                a = o.toString();
            }
            
            TVistaPrevia.setText(a);
        } else {
            TVistaPrevia.setText("Sin seleccion");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        JS = new javax.swing.JScrollPane();
        L = new javax.swing.JList();
        BCargar = new javax.swing.JButton();
        BCambiarNombre = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        BCambiarInformacion = new javax.swing.JButton();
        BCargarDirecciones = new javax.swing.JButton();
        BGuardarDirecciones = new javax.swing.JButton();
        SPVistaPrevia = new javax.swing.JScrollPane();
        TVistaPrevia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        L.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        L.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SeleccionarList(evt);
            }
        });
        JS.setViewportView(L);

        PTodo.add(JS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 280));

        BCargar.setText("Cargar");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });
        PTodo.add(BCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 140, -1));

        BCambiarNombre.setText("Cambiar Nombre");
        BCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambiarNombreActionPerformed(evt);
            }
        });
        PTodo.add(BCambiarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        PTodo.add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, -1));

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PTodo.add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, -1));

        BCambiarInformacion.setText("Cambiar Informacion");
        BCambiarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambiarInformacionActionPerformed(evt);
            }
        });
        PTodo.add(BCambiarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, -1));

        BCargarDirecciones.setText("Cargar Direcciones");
        BCargarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BCargarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 140, -1));

        BGuardarDirecciones.setText("guardar Direcciones");
        BGuardarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BGuardarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, -1));

        TVistaPrevia.setEditable(false);
        TVistaPrevia.setColumns(20);
        TVistaPrevia.setRows(5);
        SPVistaPrevia.setViewportView(TVistaPrevia);

        PTodo.add(SPVistaPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarList(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SeleccionarList
        seguridad();
    }//GEN-LAST:event_SeleccionarList

    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        ac.aceptar_Y_cargar();
    }//GEN-LAST:event_BCargarActionPerformed

    private void BCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambiarNombreActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog("Escriba el nuevo nombre de la direccion", getNombreSelecionado());
        if (nuevoNombre != null && !nuevoNombre.isEmpty()) {
            try {
                A.canviarNombre((String) L.getSelectedValue(), nuevoNombre);
                actualizarLista();
                selecionarPrimero();
                A.guardarAdminastrador(direccionAdministrador);
            } catch (Exception ex) {
                responerException(ex);
            }
        }

    }//GEN-LAST:event_BCambiarNombreActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        
        try {
            A.eliminarInformacion(getNombreSelecionado());
            actualizarLista();
            selecionarPrimero();
            seguridad();
            A.guardarAdminastrador(direccionAdministrador);
        } catch (Exception ex) {
            responerException(ex);
        }

    }//GEN-LAST:event_BEliminarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        ac.cancelar();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BCargarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarDireccionesActionPerformed
        //  JFileChooser jf = new JFileChooser();

        if (buscador(jf, this)) {
            try {
                A.addAdministrador((Admininistrador_De_Guardado<E>) Archivo.cargarArchivo(jf));
                A.guardarAdminastrador(direccionAdministrador);
                // A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(jf, new Administrador()));
                //   A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
                actualizarLista();
                selecionarPrimero();
                seguridad();
            } catch (Exception ex) {
                responerException(ex);
            }
        }
        //        A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(new Administrador()));
        //        try {
        //            A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
        //        } catch (Exception ex) {
        //            responerException(ex);
        //        }
        //        actualizarLista();
        //        selecionarPrimero();
        //        seguridad();
    }//GEN-LAST:event_BCargarDireccionesActionPerformed

    private void BGuardarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarDireccionesActionPerformed
        try {
            //   crearArchivo(A);
            JFileChooser jf = new JFileChooser();
            
            if (buscador(jf, this)) {
                crearArchivo(jf, A, EXTENCION);
            }
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BGuardarDireccionesActionPerformed

    private void BCambiarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambiarInformacionActionPerformed
        if (instancia instanceof File) {
            ventana_Canviar_Direccion = new Ventana_Cambiar_Direccion(((File) getInformacionSelecionada()).toString(), getNombreSelecionado(), A, direccionAdministrador, this);
            ventana_Canviar_Direccion.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_BCambiarInformacionActionPerformed
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        try {
            actualizar();
            selecionarPrimero();
            seguridad();
        } catch (Exception ex) {
            responerException(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana_Administrador_Configuraciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCambiarInformacion;
    private javax.swing.JButton BCambiarNombre;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BCargar;
    private javax.swing.JButton BCargarDirecciones;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardarDirecciones;
    private javax.swing.JScrollPane JS;
    private javax.swing.JList L;
    private javax.swing.JPanel PTodo;
    private javax.swing.JScrollPane SPVistaPrevia;
    private javax.swing.JTextArea TVistaPrevia;
    // End of variables declaration//GEN-END:variables
}
