/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.editor_de_subtitulos3;

import javax.swing.JTextField;
import static Aplicaciones.editor_de_subtitulos3.Ventana_Principal.*;
import Utiles.ClasesUtiles.Tiempo2.Tiempo;

import static Utiles.MetodosUtiles.MetodosUtiles.or;
import static Utiles.MetodosUtiles.MetodosUtiles.orFalse;
import static Utiles.MetodosUtiles.Visual.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.EventObject;
import javax.swing.JRadioButton;

/**
 *
 * @author Rene
 */
public class Ventana_Editar_Seccion extends javax.swing.JFrame {

    JTextField T2[];
    JRadioButton R[];

    /**
     * Creates new form Ventana_Editar_Seccion
     */
    public Ventana_Editar_Seccion() {
        this(0);
        vaciarTodo();

    }

    public Ventana_Editar_Seccion(int indice) {
        initComponents();
        T2 = new JTextField[]{TIndice, THora1, TMinuto1, TSegundos1, TMilisegundos1, THora2, TMinuto2, TSegundos2, TMilisegundos2};
        R = new JRadioButton[]{RSustituir, RdesplazarElResto, RColocarAlFinal, RColocarAlComienzo};
        for (int i = 0; i < R.length; i++) {
            BG.add(R[i]);
        }
        for (int i = 0; i < T2.length; i++) {
            T2[i].addKeyListener(new KeyAdapter() {

                @Override
                public void keyReleased(KeyEvent e) {
                    seguridad();
                }

            });
        }
        actualizar(indice);
        setLocationRelativeTo(null);
        seguridad();
        todasLasVentanas[2]=this;
    }

    private Tiempo getInferior() {
        return extraerTiempo(Arrays.asList(T2).subList(1, 5).toArray(new JTextField[]{}));
    }

    private Tiempo getSuperior() {
        return extraerTiempo(Arrays.asList(T2).subList(5, T2.length).toArray(new JTextField[]{}));
    }

    private void vaciarTodo() {
        for (int i = 0; i < T2.length; i++) {
            T2[i].setText(i == 0 ? "1" : "0");
        }
        Ta.setText("");
        seguridad();
    }

    private void actualizar(int indice) {
        // System.out.println("indice="+indice);
        T2[0].setText((indice + 1) + "");
        for (int i = 1; i < T2.length; i++) {
            actualizarT(indice, i);
        }
        Ta.setText(S.S[indice].getDialogo());
    }

    private void actualizarT(int indice, int indiceComponente) {
        T2[indiceComponente].setText(String.format("%0" + (or(indiceComponente, 4, 8) ? 4 : 2) + "d", S.S[indice].getTiempo(indiceComponente - 1)));
    }

    private void seguridad() {

        boolean tiemposSeguros = seguridadJTextField(INT, true, 0, S.sise(), BAceptar, TIndice);
        tiemposSeguros = orFalse(tiemposSeguros, seguridadJTextField(new String[]{TIEMPO60, TIEMPO60, TIEMPO60, MSEGUNDOS, TIEMPO60, TIEMPO60, TIEMPO60, MSEGUNDOS}, BAceptar, Arrays.asList(T2).subList(1, T2.length).toArray(new JTextField[]{})));
        if (tiemposSeguros) {
            tiemposSeguros = seguridadLogica();
            actualizarLLogica(tiemposSeguros);
        }
        activarJComponent(tiemposSeguros, BAceptar);
        TIndice.setEnabled(!(RColocarAlFinal.isSelected() || RColocarAlComienzo.isSelected()));

    }

    private boolean seguridadLogica() {
        return getInferior().menorQue(getSuperior());
    }

    private void actualizarLLogica(boolean correcto) {
        LLogica.setText(correcto ? "" : "El tiempo final tiene que ser mayor que el inicial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.ButtonGroup();
        PTodo = new javax.swing.JPanel();
        LSN = new javax.swing.JLabel();
        LIndice = new javax.swing.JLabel();
        RSustituir = new javax.swing.JRadioButton();
        TIndice = new javax.swing.JTextField();
        RdesplazarElResto = new javax.swing.JRadioButton();
        RColocarAlFinal = new javax.swing.JRadioButton();
        RColocarAlComienzo = new javax.swing.JRadioButton();
        TMinuto1 = new javax.swing.JTextField();
        THora1 = new javax.swing.JTextField();
        TMilisegundos1 = new javax.swing.JTextField();
        TSegundos1 = new javax.swing.JTextField();
        THora2 = new javax.swing.JTextField();
        TMinuto2 = new javax.swing.JTextField();
        TSegundos2 = new javax.swing.JTextField();
        TMilisegundos2 = new javax.swing.JTextField();
        L2P = new javax.swing.JLabel();
        L2P1 = new javax.swing.JLabel();
        L2P2 = new javax.swing.JLabel();
        L2P3 = new javax.swing.JLabel();
        LCo = new javax.swing.JLabel();
        LCo1 = new javax.swing.JLabel();
        LFlecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ta = new javax.swing.JTextArea();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        LLogica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar seccion");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                CerroVentana(evt);
            }
        });

        PTodo.setToolTipText("Edicion de Seccion de Subtitulo");
        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LSN.setText("Escriba solo números");
        PTodo.add(LSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        LIndice.setText("Indice");
        PTodo.add(LIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        RSustituir.setSelected(true);
        RSustituir.setText("sustituir");
        PTodo.add(RSustituir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        TIndice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TIndice.setText("0");
        TIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIndiceActionPerformed(evt);
            }
        });
        PTodo.add(TIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, -1));

        RdesplazarElResto.setText("desplazar el resto");
        PTodo.add(RdesplazarElResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        RColocarAlFinal.setText("colocar al final");
        PTodo.add(RColocarAlFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        RColocarAlComienzo.setText("colocar al comienzo");
        PTodo.add(RColocarAlComienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        TMinuto1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMinuto1.setText("0");
        PTodo.add(TMinuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 30, -1));

        THora1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        THora1.setText("0");
        PTodo.add(THora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, -1));

        TMilisegundos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMilisegundos1.setText("0");
        PTodo.add(TMilisegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 50, -1));

        TSegundos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TSegundos1.setText("0");
        PTodo.add(TSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, -1));

        THora2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        THora2.setText("0");
        PTodo.add(THora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 30, -1));

        TMinuto2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMinuto2.setText("0");
        PTodo.add(TMinuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 30, -1));

        TSegundos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TSegundos2.setText("0");
        PTodo.add(TSegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 30, -1));

        TMilisegundos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMilisegundos2.setText("0");
        PTodo.add(TMilisegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 50, -1));

        L2P.setText(" :");
        PTodo.add(L2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 10, 30));

        L2P1.setText(" :");
        PTodo.add(L2P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 10, 30));

        L2P2.setText(" :");
        PTodo.add(L2P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 10, 30));

        L2P3.setText(" :");
        PTodo.add(L2P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 10, 30));

        LCo.setText(" , ");
        PTodo.add(LCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 10, 30));

        LCo1.setText(" , ");
        PTodo.add(LCo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));

        LFlecha.setText("    → ");
        PTodo.add(LFlecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 40, 30));

        Ta.setColumns(20);
        Ta.setRows(5);
        jScrollPane1.setViewportView(Ta);

        PTodo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 370, 100));

        BAceptar.setText("Aceptar");
        BAceptar.setEnabled(false);
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });
        PTodo.add(BAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 120, -1));

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PTodo.add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, -1));

        LLogica.setForeground(new java.awt.Color(204, 0, 0));
        PTodo.add(LLogica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIndiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIndiceActionPerformed

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        Seccion_De_Subtitulo s1 = S.crearSeccion(Integer.parseInt(T2[4].getText()), Integer.parseInt(T2[8].getText()), Integer.parseInt(T2[3].getText()), Integer.parseInt(T2[7].getText()), Integer.parseInt(T2[2].getText()), Integer.parseInt(T2[5].getText()), Integer.parseInt(T2[1].getText()), Integer.parseInt(T2[5].getText()), Ta.getText() + "\n");
        if (RSustituir.isSelected()) {
            S.añadirSeccion(s1, Integer.parseInt(TIndice.getText()) - 1);
        }
        if (RdesplazarElResto.isSelected()) {
            S.S = S.añadirUnElemento(Integer.parseInt(TIndice.getText()) - 1, s1);
        }
        if (RColocarAlFinal.isSelected()) {
            S.añadirSeccion(s1);
        }
        if (RColocarAlComienzo.isSelected()) {
            S.S = S.añadirUnElemento(0, s1);
        }
        S.ordernar();
        ventana_Principal.actualizarT();
        visualizarVentanPrincipal();     // TODO add your handling code here:
    }//GEN-LAST:event_BAceptarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        visualizarVentanPrincipal();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void CerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CerroVentana
        setVisible(false);
        ventana_Principal.seguridad();
    }//GEN-LAST:event_CerroVentana
    private void visualizarVentanPrincipal() {
        ventana_Principal.setVisible(true);
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Editar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Editar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Editar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Editar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Editar_Seccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BCancelar;
    private javax.swing.ButtonGroup BG;
    private javax.swing.JLabel L2P;
    private javax.swing.JLabel L2P1;
    private javax.swing.JLabel L2P2;
    private javax.swing.JLabel L2P3;
    private javax.swing.JLabel LCo;
    private javax.swing.JLabel LCo1;
    private javax.swing.JLabel LFlecha;
    private javax.swing.JLabel LIndice;
    private javax.swing.JLabel LLogica;
    private javax.swing.JLabel LSN;
    private javax.swing.JPanel PTodo;
    private javax.swing.JRadioButton RColocarAlComienzo;
    private javax.swing.JRadioButton RColocarAlFinal;
    private javax.swing.JRadioButton RSustituir;
    private javax.swing.JRadioButton RdesplazarElResto;
    private javax.swing.JTextField THora1;
    private javax.swing.JTextField THora2;
    private javax.swing.JTextField TIndice;
    private javax.swing.JTextField TMilisegundos1;
    private javax.swing.JTextField TMilisegundos2;
    private javax.swing.JTextField TMinuto1;
    private javax.swing.JTextField TMinuto2;
    private javax.swing.JTextField TSegundos1;
    private javax.swing.JTextField TSegundos2;
    private javax.swing.JTextArea Ta;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
