/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.editor_de_subtitulos3;

import Aplicaciones.editor_de_subtitulos3.*;
//import Utiles.ClasesUtiles.Tiempo;
import static Utiles.MetodosUtiles.Arreglos.arregloObject;

import static Utiles.MetodosUtiles.Visual.*;
//import java.awt.event.KeyEvent;
//import javax.swing.JButton;
//import javax.swing.JTextField;
import static Aplicaciones.editor_de_subtitulos3.Ventana_Principal.*;
import Utiles.ClasesUtiles.Tiempo2.Tiempo;
import Utiles.MetodosUtiles.MetodosUtiles;

import javax.swing.JComponent;

/**
 *
 * @author Rene
 */
public class Ventana_Calcular extends javax.swing.JFrame {

    static Tiempo arriba = new Tiempo(0, 0, 0, 0);
    static Tiempo debajo = new Tiempo(0, 0, 0, 0);
    static Tiempo respuesta = new Tiempo(0, 0, 0, 0);
    int hora = 0;
    int minuto = 0;
    int segundo = 0;
    int mSegundo = 0;
    int indice = 0;
    int hora2 = 0;
    int minuto2 = 0;
    int segundo2 = 0;
    int mSegundo2 = 0;
    int indice2 = 0;

    /**
     * Creates new form Ventana_Calcular
     */
    public Ventana_Calcular() {
        initComponents();
        setLocation(600, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        todasLasVentanas[3]=this;
    }

    public boolean seguridad() {
//        boolean tiemposSeguros = seguridadJTextField(new String[]{TIEMPO60, TIEMPO60, MSEGUNDOS, MSEGUNDOS, TIEMPO60, TIEMPO60, TIEMPO60, TIEMPO60}, new JComponent[]{BCopiar, BMas, BMenos}, THoras1, THoras2, TMilisegundos1, TMilisegundos2, TMinutos1, TMinutos2, TSegundos1, TSegundos2);
//        return tiemposSeguros;
         
        return seguridadJTextField(new String[]{TIEMPO60, TIEMPO60, MSEGUNDOS, MSEGUNDOS, TIEMPO60, TIEMPO60, TIEMPO60, TIEMPO60}, new JComponent[]{BCopiar, BMas, BMenos}, THoras1, THoras2, TMilisegundos1, TMilisegundos2, TMinutos1, TMinutos2, TSegundos1, TSegundos2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PTodo = new javax.swing.JPanel();
        THoras2 = new javax.swing.JTextField();
        TMinutos2 = new javax.swing.JTextField();
        TSegundos2 = new javax.swing.JTextField();
        TMilisegundos2 = new javax.swing.JTextField();
        LHoras1 = new javax.swing.JLabel();
        THoras1 = new javax.swing.JTextField();
        TMinutos1 = new javax.swing.JTextField();
        LMinutos1 = new javax.swing.JLabel();
        TSegundos1 = new javax.swing.JTextField();
        LSegundos1 = new javax.swing.JLabel();
        LMilisegundos1 = new javax.swing.JLabel();
        TMilisegundos1 = new javax.swing.JTextField();
        BMenos = new javax.swing.JButton();
        BMas = new javax.swing.JButton();
        BAtras = new javax.swing.JButton();
        BCopiar = new javax.swing.JButton();
        LRespuesta = new javax.swing.JLabel();
        LLogica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular Tiempos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                seCerro(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        THoras2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        THoras2.setText("0");
        THoras2.setToolTipText("Horas\n");
        THoras2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(THoras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, -1));

        TMinutos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMinutos2.setText("0");
        TMinutos2.setToolTipText("Minutos");
        TMinutos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 30, -1));

        TSegundos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TSegundos2.setText("0");
        TSegundos2.setToolTipText("Segundos");
        TSegundos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TSegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, -1));

        TMilisegundos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMilisegundos2.setText("0");
        TMilisegundos2.setToolTipText("Milisegundos");
        TMilisegundos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TMilisegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 40, -1));

        LHoras1.setText("Horas");
        PTodo.add(LHoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        THoras1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        THoras1.setText("0");
        THoras1.setToolTipText("Horas\n");
        THoras1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(THoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, -1));

        TMinutos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMinutos1.setText("0");
        TMinutos1.setToolTipText("Minutos");
        TMinutos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        LMinutos1.setText("Minutos");
        PTodo.add(LMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        TSegundos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TSegundos1.setText("0");
        TSegundos1.setToolTipText("Segundos");
        TSegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 30, -1));

        LSegundos1.setText("Segundos");
        PTodo.add(LSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        LMilisegundos1.setText("Milisegundos");
        PTodo.add(LMilisegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        TMilisegundos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TMilisegundos1.setText("0");
        TMilisegundos1.setToolTipText("Milisegundos");
        TMilisegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TMilisegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, -1));

        BMenos.setText("-");
        BMenos.setToolTipText("Restar tiempo a subtitulo");
        BMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMenosPrecionarMenos(evt);
            }
        });
        PTodo.add(BMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 40, 30));

        BMas.setText("+");
        BMas.setToolTipText("Aumentar tiempo a subtitulo");
        BMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMasPrecionarMas(evt);
            }
        });
        PTodo.add(BMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        BAtras.setText("Atras");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasPrecionarCancelar(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        BCopiar.setText("Copiar");
        BCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApreatarCopiar(evt);
            }
        });
        PTodo.add(BCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        PTodo.add(LRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        LLogica.setForeground(new java.awt.Color(204, 0, 0));
        PTodo.add(LLogica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane1.setViewportView(PTodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AntesDeEscribir(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AntesDeEscribir
        eliminarTextoPredeterminado(evt, "0", THoras1, TMilisegundos1, TMinutos1, TSegundos1, THoras2, TMilisegundos2, TMinutos2, TSegundos2);
    }//GEN-LAST:event_AntesDeEscribir

    private void DespuesDeEscribir(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DespuesDeEscribir
        // if (seguridadJTextField("int", evt, arregloObject(BMenos, BMas), THoras1, TMinutos1, TSegundos1, TMilisegundos1, THoras2, TMinutos2, TSegundos2, TMilisegundos2)) {
        if (seguridad()) {
            hora = Integer.parseInt(THoras1.getText());
            minuto = Integer.parseInt(TMinutos1.getText());
            segundo = Integer.parseInt(TSegundos1.getText());
            mSegundo = Integer.parseInt(TMilisegundos1.getText());
            hora2 = Integer.parseInt(THoras2.getText());
            minuto2 = Integer.parseInt(TMinutos2.getText());
            segundo2 = Integer.parseInt(TSegundos2.getText());
            mSegundo2 = Integer.parseInt(TMilisegundos2.getText());
            arriba = new Tiempo(hora, minuto, segundo, mSegundo, true);
            debajo = new Tiempo(hora2, minuto2, segundo2, mSegundo2, true);
            boolean tiemposSeguros =seguridadLogica();
            actualizarLLogica(tiemposSeguros);
            
            activarJComponent(MetodosUtiles.orFalse(tiemposSeguros,!debajo.sonTodosCero()),BCopiar, BMas, BMenos);
        }
    }//GEN-LAST:event_DespuesDeEscribir

    private void BMenosPrecionarMenos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMenosPrecionarMenos
        respuesta = arriba.copia();
        respuesta.restar(debajo);
        LRespuesta.setText(respuesta.toString());
    }//GEN-LAST:event_BMenosPrecionarMenos

    private void BMasPrecionarMas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMasPrecionarMas
        respuesta = arriba.copia();
        respuesta.aumentar(debajo);
        LRespuesta.setText(respuesta.toString());
    }//GEN-LAST:event_BMasPrecionarMas

    private void BAtrasPrecionarCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasPrecionarCancelar
        setVisible(false);
        activarSeguridadExterna();
    }//GEN-LAST:event_BAtrasPrecionarCancelar

    private void ApreatarCopiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApreatarCopiar
        respuesta.volverPostivo();
        visualizarVentanaAumento();
        activarSeguridadExterna();
    }//GEN-LAST:event_ApreatarCopiar

    private void seCerro(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_seCerro
        activarSeguridadExterna();
    }//GEN-LAST:event_seCerro
    private void visualizarVentanaAumento() {
        if (ventana_Aumento2 == null) {
            ventana_Aumento2 = new Ventana_Aumento2();
        }
        ventana_Aumento2.escribir(respuesta);
        ventana_Aumento2.setVisible(true);
    }

    private void activarSeguridadExterna() {
        //System.out.println("se llamo");
        if (ventana_Aumento2 != null) {
            //   System.out.println("llamo");
            ventana_Aumento2.seguridad();
        }
        if (ventana_Principal != null) {
            ventana_Principal.seguridad();
        }

    }

//    private Tiempo getInferior() {
//        return extraerTiempo(tiemposIniciales);
//    }
//
//    private Tiempo getSuperior() {
//        return extraerTiempo(tiemposFinales);
//    }
    private boolean seguridadLogica() {
        return debajo.menorQue(arriba);
    }

    private void actualizarLLogica(boolean correcto) {
        LLogica.setText(correcto ? "" : "El tiempo final tiene que ser mayor que el inicial");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BCopiar;
    private javax.swing.JButton BMas;
    private javax.swing.JButton BMenos;
    private javax.swing.JLabel LHoras1;
    private javax.swing.JLabel LLogica;
    private javax.swing.JLabel LMilisegundos1;
    private javax.swing.JLabel LMinutos1;
    private javax.swing.JLabel LRespuesta;
    private javax.swing.JLabel LSegundos1;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField THoras1;
    private javax.swing.JTextField THoras2;
    private javax.swing.JTextField TMilisegundos1;
    private javax.swing.JTextField TMilisegundos2;
    private javax.swing.JTextField TMinutos1;
    private javax.swing.JTextField TMinutos2;
    private javax.swing.JTextField TSegundos1;
    private javax.swing.JTextField TSegundos2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
