/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.modificarextencion;

import Utiles.Exepciones.*;
import static Utiles.MetodosUtiles.Archivo.*;
import static Utiles.MetodosUtiles.Visual.*;
import static Utiles.MetodosUtiles.MetodosUtiles.esNumero;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Aplicaciones.modificarextencion.ModificarExtencion.*;
//import Utiles.ClasesUtiles.Admininistrador_De_Guardado;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author Rene
 */
public class Ventana_Direcciones extends javax.swing.JFrame {

    Administrador A;
    //   String direccionAdministrador;

    /**
     * Creates new form Ventana_Direcciones
     */
    public Ventana_Direcciones() throws IOException, ClassNotFoundException {
        initComponents();
        // this.direccionAdministrador = direccionAdministrador;
        A = new Administrador(DIRECCION_ADMINISTRADOR_DIRECCIONES);
        actualizarLista();
        setLocationRelativeTo(null);
//        if (L.getComponentCount() != 0) {
//            L.setSelectedIndex(0);
//        }
        selecionarPrimero();
        seguridad();
        todasLasVentanas[1]=this;
    }

    public void selecionarPrimero() {
        if (L.getComponentCount() != 0) {
            L.setSelectedIndex(0);
        }
    }

    public void actualizarLista() {
        L.setListData(A.getNombres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        L = new javax.swing.JList();
        T = new javax.swing.JTextField();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        BCargar = new javax.swing.JButton();
        BCanviarNombre = new javax.swing.JButton();
        BAtras = new javax.swing.JButton();
        BC = new javax.swing.JButton();
        BB = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCanviarDireccion = new javax.swing.JButton();
        LDirecciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BCargarDirecciones = new javax.swing.JButton();
        BGuardarDirecciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Direcciones");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        L.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                apretarLista(evt);
            }
        });
        jScrollPane1.setViewportView(L);

        PTodo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 350));

        T.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 140, -1));

        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B0, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        BCargar.setText("Cargar");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });
        PTodo.add(BCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 140, -1));

        BCanviarNombre.setText("Canviar Nombre");
        BCanviarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCanviarNombreActionPerformed(evt);
            }
        });
        PTodo.add(BCanviarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        BAtras.setText("Retroceder");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 140, -1));

        BC.setText("C");
        BC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCActionPerformed(evt);
            }
        });
        PTodo.add(BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        BB.setText("B");
        BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBActionPerformed(evt);
            }
        });
        PTodo.add(BB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        PTodo.add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 140, -1));

        BCanviarDireccion.setText("Canviar Direccion");
        BCanviarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCanviarDireccionActionPerformed(evt);
            }
        });
        PTodo.add(BCanviarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, -1));

        LDirecciones.setText("Direcciones");
        PTodo.add(LDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel1.setText("PIN de 4 dígitos");
        PTodo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        BCargarDirecciones.setText("Cargar Direcciones");
        BCargarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BCargarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 140, -1));

        BGuardarDirecciones.setText("guardar Direcciones");
        BGuardarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BGuardarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        try {
            ventanaPrincipal.setDireccion(A.getDireccion((String) L.getSelectedValue(), Integer.parseInt(T.getText())));
            visualizarVentanaPrincipal();
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BCargarActionPerformed

    private void BCanviarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCanviarNombreActionPerformed

        String nuevoNombre = JOptionPane.showInputDialog("Escriba el nuevo nombre de la direccion");
        if (nuevoNombre != null && !nuevoNombre.isEmpty()) {
            try {
                A.canviarNombre((String) L.getSelectedValue(), Integer.parseInt(T.getText()), nuevoNombre);
                actualizarLista();
                A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
            } catch (Exception ex) {
                responerException(ex);
            }
        }


    }//GEN-LAST:event_BCanviarNombreActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        try {
            A.remove((String) L.getSelectedValue(), Integer.parseInt(T.getText()));
            actualizarLista();
            A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
            seguridad();
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        visualizarVentanaPrincipal();

    }//GEN-LAST:event_BAtrasActionPerformed

    private void BCanviarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCanviarDireccionActionPerformed
        try {

//            JFileChooser jf = new JFileChooser(A.getDireccion(getNombreSelecionado(), getPINescrito()));
//            if (buscador(jf, this)) {
//                A.canviarDireccion(getNombreSelecionado(), getPINescrito(), jf.getSelectedFile() + "");
//                actualizarLista();
//                A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
//            }
          visualizarCanviarDireccion();
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BCanviarDireccionActionPerformed

    private void SoltarTeclado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoltarTeclado
        acortarPIN();
        seguridad();

    }//GEN-LAST:event_SoltarTeclado

    private void apretarLista(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_apretarLista
        seguridad();
    }//GEN-LAST:event_apretarLista

    private void BCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCActionPerformed
        T.setText("");
        seguridad();
    }//GEN-LAST:event_BCActionPerformed

    private void BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBActionPerformed
        Backspace(T);
        seguridad();
    }//GEN-LAST:event_BBActionPerformed

    private void apretarDigito(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apretarDigito
        T.setText(T.getText() + evt.getActionCommand());
        acortarPIN();
        seguridad();
    }//GEN-LAST:event_apretarDigito

    private void BCargarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarDireccionesActionPerformed
        JFileChooser jf = new JFileChooser();

        if (buscador(jf, this)) {
            try {
                A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(jf, new Administrador()));
                A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
                actualizarLista();
                selecionarPrimero();
                seguridad();
            } catch (Exception ex) {
                responerException(ex);
            }
        }
//        A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(new Administrador()));
//        try {
//            A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
//        } catch (Exception ex) {
//            responerException(ex);
//        }
//        actualizarLista();
//        selecionarPrimero();
//        seguridad();
    }//GEN-LAST:event_BCargarDireccionesActionPerformed

    private void BGuardarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarDireccionesActionPerformed
        try {
            //   crearArchivo(A);
            JFileChooser jf = new JFileChooser();

            if (buscador(jf, this)) {
                crearArchivo(jf, A,".dir");
            }
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BGuardarDireccionesActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
         ventanaPrincipal.alCerrar(this);
    }//GEN-LAST:event_cerroVentana
//    public synchronized String nuevaDireccion() throws InterruptedException, NoEncontradoException, PINException {
//        Object comunicacion = "";
//        ventanaCanviarDireccion = new Ventana_Canviar_Direccion(A.getDireccion(getNombreSelecionado(), getPINescrito()) + "", comunicacion);
//        Thread t=new Thread(ventanaCanviarDireccion);
//        t.run();
//       // ventanaCanviarDireccion.setVisible(true);
//        //Thread.
//       wait();
//        return (String) comunicacion;
//
//    }

    public void visualizarCanviarDireccion() throws NoEncontradoException, PINException {
        ventanaCanviarDireccion = new Ventana_Canviar_Direccion(A.getDireccion(getNombreSelecionado(), getPINescrito()) + "", getNombreSelecionado(), getPINescrito(), A);
        //System.out.println("visible");
        ventanaCanviarDireccion.setVisible(true);
        setVisible(false);
      //  setFocusableWindowState(false);
    }

    public String getNombreSelecionado() {
        return (String) L.getSelectedValue();
    }

    public int getPINescrito() {
        return Integer.parseInt(T.getText());
    }

    public void acortarPIN() {
        if (T.getText().length() > 4) {
            T.setText(T.getText().substring(0, 4));
        }
    }

    private void responerException(Exception ex) {
        if (ex instanceof NoEncontradoException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof PINException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof ExisteException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof IOException) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el archibo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("respuesta");
        ex.printStackTrace();
    }

    private void visualizarVentanaPrincipal() {
        ventanaPrincipal.seguridad();
        ventanaPrincipal.setVisible(true);
        setVisible(false);
    }

    private void seguridad() {
        seguridadJTextField(!T.getText().isEmpty() && T.getText().length() == 4 && esNumero(T.getText()) && L.getComponentCount() != 0 && L.getSelectedIndex() != -1, T, BCanviarDireccion, BCanviarNombre, BCargar, BEliminar);
        seguridadJList(L, BGuardarDirecciones);
//        System.out.println("--------------------");
//        System.out.println("!T.getText().isEmpty()=" + !T.getText().isEmpty());
//        System.out.println("T.getText().length() == 4 =" + (T.getText().length() == 4));
//        System.out.println("esNumero(T.getText())=" + esNumero(T.getText()));
//        System.out.println("L.getComponentCount() != 0 =" + (L.getComponentCount() != 0));
//        System.out.println("L.getSelectedIndex() != -1=" + (L.getSelectedIndex() != -1));
        //seguridadJTextField(T, L, BCanviarDireccion,BCanviarNombre,BCargar,BEliminar);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana_Direcciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BB;
    private javax.swing.JButton BC;
    private javax.swing.JButton BCanviarDireccion;
    private javax.swing.JButton BCanviarNombre;
    private javax.swing.JButton BCargar;
    private javax.swing.JButton BCargarDirecciones;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardarDirecciones;
    private javax.swing.JList L;
    private javax.swing.JLabel LDirecciones;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField T;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
