/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.modificarextencion;

import Utiles.Exepciones.ExisteException;
import Utiles.Exepciones.NoEncontradoException;
import Utiles.Exepciones.PINException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Aplicaciones.modificarextencion.ModificarExtencion.*;
import static Utiles.MetodosUtiles.Visual.*;
import static Utiles.MetodosUtiles.MetodosUtiles.esPIN;
import java.io.File;
import javax.swing.JTextField;

/**
 *
 * @author Rene
 */
public class Ventana_Nueva_Direccion extends javax.swing.JFrame {

   // String direccionAdministrador;

    /**
     * Creates new form Ventana_Nueva_Direccion
     */
    public Ventana_Nueva_Direccion( String direccion) {
       // this.direccionAdministrador = direccionAdministrador;
        initComponents();
        TDireccion.setText(direccion);
        setLocationRelativeTo(null);
        seguridad();
        todasLasVentanas[2]=this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        BB = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        BC = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        TPIN = new javax.swing.JTextField();
        TDireccion = new javax.swing.JTextField();
        TNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BAtras = new javax.swing.JButton();
        BCrearDireccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BB.setText("B");
        BB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBActionPerformed(evt);
            }
        });
        PTodo.add(BB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        BC.setText("C");
        BC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCActionPerformed(evt);
            }
        });
        PTodo.add(BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apretarDigito(evt);
            }
        });
        PTodo.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        TPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soltarTecladoPIN(evt);
            }
        });
        PTodo.add(TPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        TDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soltarTecladoDireccion(evt);
            }
        });
        PTodo.add(TDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, -1));

        TNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soltarTecladoNombre(evt);
            }
        });
        PTodo.add(TNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 140, -1));

        jLabel1.setText("PIN de 4 dígitos");
        PTodo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setText("Nombre");
        PTodo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel3.setText("Direccion");
        PTodo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        BAtras.setText("Retroceder");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, -1));

        BCrearDireccion.setText("Crear Direccion");
        BCrearDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearDireccionActionPerformed(evt);
            }
        });
        PTodo.add(BCrearDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        visualizarVentanaPrincipal();
    }//GEN-LAST:event_BAtrasActionPerformed

    private void BCrearDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearDireccionActionPerformed
        try {
            Administrador A = new Administrador(DIRECCION_ADMINISTRADOR_DIRECCIONES);
            A.addDireccion(TNombre.getText().trim(), new Direccion(TDireccion.getText().trim(), Integer.parseInt(TPIN.getText().trim())));
            A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
            visualizarDirecciones();
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BCrearDireccionActionPerformed

    private void soltarTecladoDireccion(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soltarTecladoDireccion
        seguridad();
    }//GEN-LAST:event_soltarTecladoDireccion

    private void soltarTecladoPIN(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soltarTecladoPIN
        acortarPIN();
        seguridad();

    }//GEN-LAST:event_soltarTecladoPIN

    private void soltarTecladoNombre(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soltarTecladoNombre
        seguridad();
    }//GEN-LAST:event_soltarTecladoNombre

    private void apretarDigito(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apretarDigito
       TPIN.setText(TPIN.getText()+evt.getActionCommand());
       acortarPIN();
       seguridad();
    }//GEN-LAST:event_apretarDigito

    private void BCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCActionPerformed
      TPIN.setText("");
      seguridad();
    }//GEN-LAST:event_BCActionPerformed

    private void BBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBActionPerformed
        Backspace(TPIN);
        seguridad();
    }//GEN-LAST:event_BBActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
        ventanaPrincipal.alCerrar(this);
    }//GEN-LAST:event_cerroVentana

    public void acortarPIN(){
    if (TPIN.getText().length() > 4) {
            TPIN.setText(TPIN.getText().substring(0,4));
        }
    }
    
    public void seguridad() {
       // eliminarEspaciosDelPrincipioJTextField(TDireccion, TNombre, TPIN);
        seguridadJTextField(new boolean[]{!TDireccion.getText().isEmpty()&& new File(TDireccion.getText().trim()).exists(),!TNombre.getText().isEmpty(),esPIN(TPIN.getText().trim())},BCrearDireccion, TDireccion, TNombre, TPIN);
       // seguridadJTextField(esPIN(TPIN.getText()) && !TNombre.getText().isEmpty() && !TDireccion.getText().isEmpty() && new File(TDireccion.getText()).exists(), BCrearDireccion, TDireccion, TNombre, TPIN);
    }

    private void responerException(Exception ex) {
        if (ex instanceof NoEncontradoException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof PINException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof ExisteException) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ex instanceof IOException) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el archibo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ex instanceof ClassNotFoundException) {
            JOptionPane.showMessageDialog(this, "El archibo de guardado presenta problemas", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ex.printStackTrace();
    }

    private void visualizarVentanaPrincipal() {
        ventanaPrincipal.setVisible(true);
        setVisible(false);
    }

    private void visualizarDirecciones() throws IOException, ClassNotFoundException {
        ventanaDirecciones = new Ventana_Direcciones();
        ventanaDirecciones.setVisible(true);
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nueva_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nueva_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nueva_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nueva_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana_Nueva_Direccion().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BB;
    private javax.swing.JButton BC;
    private javax.swing.JButton BCrearDireccion;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField TDireccion;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TPIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
