/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.convertir;

import Utiles.ClasesUtiles.Medidas.TipoDeMedida;
import static Utiles.MetodosUtiles.Visual.*;
import static Utiles.MetodosUtiles.Arreglos.arregloObject;
import static Utiles.MetodosUtiles.MetodosUtiles.ArregloAStringArreglo;
import static Utiles.MetodosUtiles.MetodosUtiles.eliminarPuntoCero;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import static todo.Todo.*;
/**
 *
 * @author Rene
 */
public class Ventana_Principal extends javax.swing.JFrame {

    Convertidor convertidor = new Convertidor();

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
        setLocation(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PTodo = new javax.swing.JPanel();
        LLaberinto = new javax.swing.JLabel();
        LMedida = new javax.swing.JLabel();
        CTipoDeMedida = new javax.swing.JComboBox();
        LDesde = new javax.swing.JLabel();
        CUnidadInicial = new javax.swing.JComboBox();
        La = new javax.swing.JLabel();
        CUnidadFinal = new javax.swing.JComboBox();
        TEntrada = new javax.swing.JTextField();
        TSalida = new javax.swing.JTextField();
        BConvertir = new javax.swing.JButton();
        BAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Convertidor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LLaberinto.setFont(new java.awt.Font("Blackadder ITC", 1, 36)); // NOI18N
        LLaberinto.setText("Convertir");
        PTodo.add(LLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LMedida.setText("Medida");
        PTodo.add(LMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        CTipoDeMedida.setModel(new javax.swing.DefaultComboBoxModel(ArregloAStringArreglo(TipoDeMedida.values())));
        CTipoDeMedida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelecionarMedida(evt);
            }
        });
        PTodo.add(CTipoDeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        LDesde.setText("Desde");
        PTodo.add(LDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        CUnidadInicial.setModel(new javax.swing.DefaultComboBoxModel(TipoDeMedida.values()[0].getUnidadesString()));
        CUnidadInicial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelecionarUnidadBase(evt);
            }
        });
        PTodo.add(CUnidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        La.setText("a");
        PTodo.add(La, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        CUnidadFinal.setModel(new javax.swing.DefaultComboBoxModel(TipoDeMedida.values()[0].getUnidadesString()));
        CUnidadFinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelecionarUnidadRespuesta(evt);
            }
        });
        PTodo.add(CUnidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        TEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TEntrada.setText("0");
        TEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AntesDeEscribir(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribir(evt);
            }
        });
        PTodo.add(TEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, -1));

        TSalida.setEditable(false);
        TSalida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TSalida.setText("0");
        PTodo.add(TSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, -1));

        BConvertir.setText("Convertir");
        BConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConvertirActionPerformed(evt);
            }
        });
        PTodo.add(BConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        BAtras.setText("Atras");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setViewportView(PTodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AntesDeEscribir(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AntesDeEscribir
        eliminarTextoPredeterminado(evt, "0", TEntrada);
    }//GEN-LAST:event_AntesDeEscribir

    private void DespuesDeEscribir(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DespuesDeEscribir
        seguridadJTextField("double", evt, arregloObject(BConvertir), TEntrada);
    }//GEN-LAST:event_DespuesDeEscribir

    private void BConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConvertirActionPerformed
        //convertidor.convertir(Double.parseDouble(TEntrada.getText())) + ""
        TSalida.setText(eliminarPuntoCero(convertidor.convertir(Double.parseDouble(TEntrada.getText())) + ""));
    }//GEN-LAST:event_BConvertirActionPerformed

    private void SelecionarMedida(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelecionarMedida
        convertidor.setIndiceMedidaActual(CTipoDeMedida.getSelectedIndex());
        
        
          if (evt.getStateChange() == ItemEvent.SELECTED) {
          //  System.out.println("");
            //convertidor.setIndiceUnidadBase(CUnidadInicial.getSelectedIndex());
            CUnidadInicial.removeAllItems();
            CUnidadFinal.removeAllItems();
            String g[] = TipoDeMedida.values()[CTipoDeMedida.getSelectedIndex()].getUnidadesString();
            for (int i = 0; i < g.length; i++) {
                CUnidadInicial.addItem(g[i]);
                CUnidadFinal.addItem(g[i]);
            }
        }
    }//GEN-LAST:event_SelecionarMedida

    private void SelecionarUnidadBase(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelecionarUnidadBase
convertidor.setIndiceUnidadBase(CUnidadInicial.getSelectedIndex());

//        if (evt.getStateChange() == ItemEvent.SELECTED) {
//            System.out.println("");
//            convertidor.setIndiceUnidadBase(CUnidadInicial.getSelectedIndex());
//            CUnidadInicial.removeAllItems();
//            CUnidadFinal.removeAllItems();
//            String g[] = TipoDeMedida.values()[CTipoDeMedida.getSelectedIndex()].getUnidadesString();
//            for (int i = 0; i < g.length; i++) {
//                CUnidadInicial.addItem(g[i]);
//                CUnidadFinal.addItem(g[i]);
//            }
//        }

      //  CUnidadInicial.setModel(new javax.swing.DefaultComboBoxModel(TipoDeMedida.values()[CTipoDeMedida.getSelectedIndex()].getUnidadesString()));
        // CUnidadFinal.setModel(new javax.swing.DefaultComboBoxModel(TipoDeMedida.values()[CTipoDeMedida.getSelectedIndex()].getUnidadesString()));
    }//GEN-LAST:event_SelecionarUnidadBase

    private void SelecionarUnidadRespuesta(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelecionarUnidadRespuesta
        convertidor.setIndiceUnidadResultante(CUnidadFinal.getSelectedIndex());
    }//GEN-LAST:event_SelecionarUnidadRespuesta

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        maximizarVentana(ventanaTodo);
        setVisible(false);
    }//GEN-LAST:event_BAtrasActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
        alCerrar(this);
    }//GEN-LAST:event_cerroVentana

     public void alCerrar(JFrame f) {
        cerrar(f, 4);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BConvertir;
    private javax.swing.JComboBox CTipoDeMedida;
    private javax.swing.JComboBox CUnidadFinal;
    private javax.swing.JComboBox CUnidadInicial;
    private javax.swing.JLabel LDesde;
    private javax.swing.JLabel LLaberinto;
    private javax.swing.JLabel LMedida;
    private javax.swing.JLabel La;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField TEntrada;
    private javax.swing.JTextField TSalida;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
