/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.actualizador.de.series;

import Utiles.ClasesUtiles.Configuraciones.ConfiguracionDeVideo;
import Utiles.MetodosUtiles.MetodosUtiles;
import Utiles.MetodosUtiles.Visual;
import java.awt.Color;
import java.util.StringTokenizer;

/**
 *
 * @author Rene
 */
public class Ventana_Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Prueba
     */
    public Ventana_Prueba() {
        initComponents();

//        TA.setSelectionStart(20);
//        TA.setSelectionEnd(32);
//         TA.setSelectionColor(Color.RED);
//         TA.setSelectedTextColor(Color.red);
//        TA.cut();
//        System.out.println("SPA.getVerticalScrollBar().getValue()="+SPA.getVerticalScrollBar().getValue());
//         SPA.getVerticalScrollBar().setValue(SPA.getVerticalScrollBar().getValue()-100);
//         System.out.println("SPA.getVerticalScrollBar().getValue()="+SPA.getVerticalScrollBar().getValue());
//         SPA.set
//          SPA.getVerticalScrollBar().updateUI();
//         TA.setText("iiiiiiiiiiiiiii");

    }

    public void buscar(char a) {
        String A[] = Visual.leerJTextArea(TA);
        int ini = 0, end = -1;
        
        for (int i = 0; i < A.length; i++) {
//            System.out.println("A[i]="+A[i]);
            StringTokenizer St = new StringTokenizer(A[i]);
            if (St.hasMoreTokens() && St.nextToken().startsWith(a + "")) {
                end = ini + A[i].length()+(i!=0?1:0);
                break;
            }
            ini+=A[i].length()+(i!=0?1:0);
        }
        if(end!=-1){
        TA.setSelectionStart(ini);
        TA.setSelectionEnd(end);
        }else{
//            MetodosUtiles.pi
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        SPA = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        SPP = new javax.swing.JScrollPane();
        TP = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        TA.setText("aaaaaaaaaaaaaaaaaa\nsssssssssssssssssss\ndddddddddddd\nffffffffff\ng\nh\ni\nfffff\nj\nk\nl\nm\nn\nnnnnnn\nnn\no\np");
        TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apretoTA(evt);
            }
        });
        SPA.setViewportView(TA);

        PTodo.add(SPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 36, -1, 179));

        SPP.setViewportView(TP);
        TP.setText("aaaaaaaaaaaaaaaa\nbbbbbbbbbbbbbbbbbb\n"
            + "ccccccccccccccc\neeeeeeeeeeeeeeeeeeee");

        PTodo.add(SPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 170, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apretoTA(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apretoTA
//        buscar(evt.getKeyChar());
        Visual.señalarJTextTarea(TA, evt, ConfiguracionDeVideo.getDefault());
    }//GEN-LAST:event_apretoTA

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PTodo;
    private javax.swing.JScrollPane SPA;
    private javax.swing.JScrollPane SPP;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextPane TP;
    // End of variables declaration//GEN-END:variables
}
