/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.MoverNumero;

import Aplicaciones.MoverNumero.*;
//import Aplicaciones.MoverNumero.librerias.Estado_Actual;
import Utiles.Exepciones.ExisteException;
import Utiles.Exepciones.NoEncontradoException;
import Utiles.Exepciones.NoPermitidoException;
import Utiles.Exepciones.PINException;
import static Utiles.MetodosUtiles.Visual.*;
import static Utiles.MetodosUtiles.Archivo.*;
import java.io.File;
import java.io.FileNotFoundException;
//import static Utiles.MetodosUtiles.MetodosUtiles.*;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static Aplicaciones.MoverNumero.ModificarExtencion.*;
import Utiles.ClasesUtiles.Admininistrador.Admininistrador_De_Guardado;
import Utiles.ClasesUtiles.Admininistrador.Ventana_Administrador;
import Utiles.ClasesUtiles.Configuraciones.ConfiguracionDeVideo;
import Utiles.ClasesUtiles.Configuraciones.Ventanas.Ventana_ConfiguracionDeVideo;
import Utiles.ClasesUtiles.Interfases.Accion_Cargar_Cancelar;
import static Utiles.MetodosUtiles.Videos.activar;
import static Utiles.MetodosUtiles.Videos.capitulosQueFaltan;
import static Utiles.MetodosUtiles.Videos.desactivar;
import static Utiles.MetodosUtiles.Videos.eliminarNumeroDelPricipio;
import static Utiles.MetodosUtiles.Videos.moverNumero;
import static Utiles.MetodosUtiles.Videos.moverNumeroInverso;
import java.awt.event.ItemEvent;
import java.util.LinkedList;
import java.util.TreeSet;
import javax.swing.JFrame;
import static todo.Todo.*;

/**
 *
 * @author Rene
 */
public class Ventana_Principal extends javax.swing.JFrame {
    
    JFileChooser jf = new JFileChooser();
    ConfiguracionDeVideo cdv;
    EstadoActual EA;
    //  MoverNumeroConfiguracion conf;

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() throws IOException, ClassNotFoundException {
//      conf = (MoverNumeroConfiguracion) cargarArchivo(DIRECCION_ESTADO_ACTUAL);
        try {
            EA = (EstadoActual) cargarArchivo(DIRECCION_ESTADO_ACTUAL);
        } catch (Exception ex) {
            EA = new EstadoActual();
            crearArchivo(new File(DIRECCION_ESTADO_ACTUAL), EA);
        }
        
        cdv = EA.getT().getCdvSelecionado();
//        CInvasivo.setSelected(cdv.);
        initComponents();
        T.setText(EA.getDireccion().toString());
        seguridad();
        setLocationRelativeTo(null);
        todasLasVentanas = new JFrame[]{this, ventana_Administrador, ventana_ConfiguracionDeVideo};
    }

//    public Ventana_Principal(Estado_Actual estado_Actual) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    public Ventana_Principal(Estado_Actual estado_Actual) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    public void setDireccion(String direccion) {
        T.setText(direccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        T = new javax.swing.JTextField();
        BDirecciones = new javax.swing.JButton();
        BBuscarCarpeta = new javax.swing.JButton();
        BGuardarDireccion = new javax.swing.JButton();
        LDireccion = new javax.swing.JLabel();
        BMoverNumero = new javax.swing.JButton();
        BMoverNumeroInverso = new javax.swing.JButton();
        BEliminarNumero = new javax.swing.JButton();
        BCrearListaFaltantes = new javax.swing.JButton();
        BConfiguracion = new javax.swing.JButton();
        CInvasivo = new javax.swing.JCheckBox();
        BAtras = new javax.swing.JButton();
        CBDirecciones = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Nombres");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrandoVentana(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soltarTeclado(evt);
            }
        });
        PTodo.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 470, -1));

        BDirecciones.setText("Direcciones");
        BDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        BBuscarCarpeta.setText("Buscar Carpeta");
        BBuscarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarCarpetaActionPerformed(evt);
            }
        });
        PTodo.add(BBuscarCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        BGuardarDireccion.setText("Guardar Direccion");
        BGuardarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarDireccionActionPerformed(evt);
            }
        });
        PTodo.add(BGuardarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        LDireccion.setText("Direccion");
        PTodo.add(LDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        BMoverNumero.setText("Mover Numero de Captiulo a delante");
        BMoverNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMoverNumeroActionPerformed(evt);
            }
        });
        PTodo.add(BMoverNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, -1));

        BMoverNumeroInverso.setText("Mover Numero de Captiulo al final");
        BMoverNumeroInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMoverNumeroInversoActionPerformed(evt);
            }
        });
        PTodo.add(BMoverNumeroInverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        BEliminarNumero.setText("Eliminar Numero de capitulo de delante");
        BEliminarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarNumeroActionPerformed(evt);
            }
        });
        PTodo.add(BEliminarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 270, -1));

        BCrearListaFaltantes.setText("Lista de Capitulos Faltantes");
        BCrearListaFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearListaFaltantesActionPerformed(evt);
            }
        });
        PTodo.add(BCrearListaFaltantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 270, -1));

        BConfiguracion.setText("Configuracion");
        BConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfiguracionActionPerformed(evt);
            }
        });
        PTodo.add(BConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        CInvasivo.setText("Invasivo");
        CInvasivo.setToolTipText("si se desean que se modifiquen tambien todas las subcarpetas");
        PTodo.add(CInvasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        BAtras.setText("Atras");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CBDirecciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "   "}));
        actualizarCBDirecciones();
        CBDirecciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selecionoCBDirecciones(evt);
            }
        });
        CBDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDireccionesActionPerformed(evt);
            }
        });
        CBDirecciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SeleccionoBGDireccionesActuales(evt);
            }
        });
        PTodo.add(CBDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBuscarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarCarpetaActionPerformed
        
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        if (buscador(jf, this)) {
            T.setText(arreglarDireccion(jf.getSelectedFile().toString()));
            seguridad();
        }
    }//GEN-LAST:event_BBuscarCarpetaActionPerformed

    private void BDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDireccionesActionPerformed
//        try {
        visualizarVentanaAdministrador();
//        } catch (Exception ex) {
//            responerException(ex);
//        }
    }//GEN-LAST:event_BDireccionesActionPerformed

    private void BGuardarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarDireccionActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog("Escriba el nuevo nombre de los personalizados");
        if (nuevoNombre != null && !nuevoNombre.isEmpty()) {
            try {
                Admininistrador_De_Guardado<File> A = new Admininistrador_De_Guardado(DIRECCION_ADMINISTRADOR_DIRECCIONES);
//                LinkedList<SeccionPersonalizada> p = new LinkedList<SeccionPersonalizada>();
//                p.add(getPersonalizadosBase().get(indiceCBP()));
                A.agregarInformacion(nuevoNombre, new File(T.getText()));
                A.guardarAdminastrador(DIRECCION_ADMINISTRADOR_DIRECCIONES);
                // visualizarVentanaAdministradorDirecciones();
            } catch (Exception ex) {
                responerException(ex);
            }
        }
    }//GEN-LAST:event_BGuardarDireccionActionPerformed

    private void soltarTeclado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soltarTeclado
        seguridad();
    }//GEN-LAST:event_soltarTeclado

    private void BMoverNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMoverNumeroActionPerformed
        try {

//          moverNumero(obtenerTexto(), conf.isRenombrarCarpetaInterna(), conf.getNivelesCarpetasInternas(), conf.getAntesIngnorar(), conf.getDespuesIngnorar(), conf.getRodearIgnorarPrincipioYFin(), conf.getSaltarAlPrincipioString(), conf.getDetencionesString(), conf.getNumerosASaltar(), conf.getAntesCantidad(), conf.getDespuesCantidad(), conf.getFormato());
//            System.out.println(Arrays.toString(cdv.formato));
            moverNumero(obtenerFile(), cdv);
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BMoverNumeroActionPerformed

    private void BCrearListaFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearListaFaltantesActionPerformed
        try {
            capitulosQueFaltan(obtenerTexto(), cdv);
//            capitulosQueFaltan(obtenerTexto(), conf.getNivelesCarpetasInternas(), conf.getAntesIngnorar(), conf.getDespuesIngnorar(), conf.getRodearIgnorarPrincipioYFin(), conf.getNumerosASaltar(), conf.getAntesCantidad(), conf.getDespuesCantidad());
        } catch (Exception ex) {
            responerException(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BCrearListaFaltantesActionPerformed

    private void BMoverNumeroInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMoverNumeroInversoActionPerformed
        try {
            moverNumeroInverso(obtenerTexto());
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BMoverNumeroInversoActionPerformed

    private void BEliminarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarNumeroActionPerformed
        try {
            eliminarNumeroDelPricipio(obtenerTexto(), cdv.isRenombrarCarpetasInternas(), cdv.getNivelesCarpetasInternas());
//           eliminarNumeroDelPricipio(obtenerTexto(), conf.isRenombrarCarpetaInterna(), conf.getNivelesCarpetasInternas());
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BEliminarNumeroActionPerformed

    private void BConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfiguracionActionPerformed
        
        visualizarVentanaConfiguracion();
    }//GEN-LAST:event_BConfiguracionActionPerformed

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        maximizarVentana(ventanaTodo);
        setVisible(false);
    }//GEN-LAST:event_BAtrasActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
        alCerrar(this);
    }//GEN-LAST:event_cerroVentana

    private void selecionoCBDirecciones(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selecionoCBDirecciones
        if (evt.getStateChange() == ItemEvent.SELECTED && CBDirecciones.getSelectedIndex() != 0) {
            setDireccion(arreglarDireccion(CBDirecciones.getSelectedItem().toString().trim()));
            seguridad();
        }
    }//GEN-LAST:event_selecionoCBDirecciones

    private void CBDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDireccionesActionPerformed
        // System.out.println("se la");

    }//GEN-LAST:event_CBDireccionesActionPerformed

    private void SeleccionoBGDireccionesActuales(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SeleccionoBGDireccionesActuales
        actualizarCBDirecciones();
    }//GEN-LAST:event_SeleccionoBGDireccionesActuales

    private void cerrandoVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrandoVentana
        try {
            EA.setDireccion(new File(T.getText()));
            crearArchivo(DIRECCION_ESTADO_ACTUAL, EA);
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_cerrandoVentana
    
    public synchronized void actualizarCBDirecciones() {
        CBDirecciones.removeAllItems();
        CBDirecciones.removeAll();
        CBDirecciones.addItem("  ");
        
        for (int i = 0; i < File.listRoots().length; i++) {
            
            CBDirecciones.addItem(File.listRoots()[i].toString());
        }
        
    }
    
    public void alCerrar(JFrame f) {
        cerrar(f, 7);
        
    }
    
    public void visualizarVentanaAdministrador() {
        try {
            if (ventana_Administrador == null) {
                ventana_Administrador = new Ventana_Administrador<File>(DIRECCION_ADMINISTRADOR_DIRECCIONES, new Accion_Cargar_Cancelar() {
                    
                    @Override
                    public void aceptar_Y_cargar() {
                        T.setText(ventana_Administrador.getInformacionSelecionada().toString());
                        seguridad();
                        ventana_Administrador.setVisible(false);
                        setVisible(true);
                    }
                    
                    @Override
                    public void cancelar() {
                        ventana_Administrador.setVisible(false);
                        setVisible(true);
                    }
                });
            } else {
                ventana_Administrador.setDireccionAdministrador(DIRECCION_ADMINISTRADOR_DIRECCIONES);
            }
            ventana_Administrador.setVisible(true);
            setVisible(false);
        } catch (Exception ex) {
            responerException(ex);
        }
    }
    
    public void visualizarVentanaConfiguracion() {
        try {
            if (ventana_ConfiguracionDeVideo == null) {
                ventana_ConfiguracionDeVideo = new Ventana_ConfiguracionDeVideo(EA.getT(), DIRECCION_ADMINISTRADOR_CONFIGURACIONES, new Accion_Cargar_Cancelar() {
                    
                    @Override
                    public void aceptar_Y_cargar() {
                        EA.setT(ventana_ConfiguracionDeVideo.getTOriginal());
                        cdv = EA.getT().getCdvSelecionado();
                        ventana_ConfiguracionDeVideo.setVisible(false);
                        setVisible(true);
                    }
                    
                    @Override
                    public void cancelar() {
                        ventana_ConfiguracionDeVideo.setVisible(false);
                        setVisible(true);
                    }
                });
            } else {
                ventana_ConfiguracionDeVideo.setDireccionAdministrador(DIRECCION_ADMINISTRADOR_CONFIGURACIONES);
            }
            
            ventana_ConfiguracionDeVideo.setVisible(true);
            setVisible(false);
        } catch (Exception ex) {
            responerException(ex);
        }
        
    }
    
    public String obtenerTexto() {
        return arreglarDireccion(T.getText().trim());
    }
    
    public File obtenerFile() {
        return new File(obtenerTexto());
    }

//    public void seguridad() {
//
//        if (seguridadJTextField(T, arreglarDireccion(T.getText().trim()), BGuardarDireccion, BActivar, BDesactivar, BCrearListaFaltantes, BEliminarNumero, BMoverNumero, BMoverNumeroInverso)) {
//            File porDefecto = obtenerFile();
//            if (porDefecto.exists()) {
//                jf.setSelectedFile(porDefecto);
//            }
//        }
//    }
    public void seguridad() {
        
        if (seguridadJTextField(T, arreglarDireccion(T.getText().trim()), BGuardarDireccion, BCrearListaFaltantes, BEliminarNumero, BMoverNumero, BMoverNumeroInverso)) {
            File porDefecto = obtenerFile();
            if (porDefecto.exists()) {
                jf.setSelectedFile(porDefecto);
            }
        }
    }
//    private void visualizarDirecciones() throws IOException, ClassNotFoundException {
//        ventanaDirecciones = new Ventana_Direcciones();
//        ventanaDirecciones.setVisible(true);
//        setVisible(false);
//    }
//
//    private void visualizarNuevaDireccion() {
//        ventanaNuevaDireccion = new Ventana_Nueva_Direccion(arreglarDireccion(T.getText()));
//        ventanaNuevaDireccion.setVisible(true);
//        setVisible(false);
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BBuscarCarpeta;
    private javax.swing.JButton BConfiguracion;
    private javax.swing.JButton BCrearListaFaltantes;
    private javax.swing.JButton BDirecciones;
    private javax.swing.JButton BEliminarNumero;
    private javax.swing.JButton BGuardarDireccion;
    private javax.swing.JButton BMoverNumero;
    private javax.swing.JButton BMoverNumeroInverso;
    private javax.swing.JComboBox CBDirecciones;
    private javax.swing.JCheckBox CInvasivo;
    private javax.swing.JLabel LDireccion;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField T;
    // End of variables declaration//GEN-END:variables
}
