/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.librerias;

//import Utiles.ClasesUtiles.*;
//import Utiles.ClasesUtiles.Admininistrador_De_Guardado;
import Utiles.MetodosUtiles.Archivo;
import static Utiles.MetodosUtiles.Archivo.crearArchivo;
import java.io.IOException;
import static Utiles.MetodosUtiles.Visual.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static Aplicaciones.librerias.Librerias.*;
import javax.swing.JFrame;

/**
 * Version 0.3
 *
 * @author Rene
 */
public class Ventana_Administrador extends javax.swing.JFrame {

    Admininistrador_De_Guardado<java.io.File[]> A;
    String direccionAdministrador;
    JFileChooser jf;

    /**
     * Creates new form Ventana_Administrador_Configuraciones
     */
    public Ventana_Administrador(String direccionAdministrador) throws IOException, ClassNotFoundException {
        jf = new JFileChooser();
        this.direccionAdministrador = direccionAdministrador;
        actualizarDatos();
        initComponents();
        actualizarLista();
        setLocationRelativeTo(null);
        selecionarPrimero();
        seguridad();
    }

    public void selecionarPrimero() {
        if (L.getComponentCount() != 0) {
            L.setSelectedIndex(0);
        }
    }

    public void actualizar() throws IOException, ClassNotFoundException {
        actualizarDatos();
        actualizarLista();
    }

    public void actualizarDatos() throws IOException, ClassNotFoundException {
        A = new Admininistrador_De_Guardado(direccionAdministrador);
    }

    public void actualizarLista() {
        L.setListData(A.getNombres());
    }

    private void seguridad() {
        seguridadJList(L, BCanviarInformacion, BCanviarNombre, BCargar, BEliminar);
    }

    public String getNombreSelecionado() {
        return (String) L.getSelectedValue();
    }

    public java.io.File[] getInformacionSelecionada() {
        return (java.io.File[]) A.getInformacion(getNombreSelecionado());
    }

    private void visualizarVentanPrincipal() {
        ventana_Principal.setVisible(true);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTodo = new javax.swing.JPanel();
        JS = new javax.swing.JScrollPane();
        L = new javax.swing.JList();
        BCargar = new javax.swing.JButton();
        BCanviarNombre = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        BCanviarInformacion = new javax.swing.JButton();
        BCargarDirecciones = new javax.swing.JButton();
        BGuardarDirecciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Direcciones");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                abrioVentana(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                CerrarVentana(evt);
            }
        });

        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        L.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SeleccionarList(evt);
            }
        });
        JS.setViewportView(L);

        PTodo.add(JS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 280));

        BCargar.setText("Cargar");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });
        PTodo.add(BCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 140, -1));

        BCanviarNombre.setText("Canviar Nombre");
        BCanviarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCanviarNombreActionPerformed(evt);
            }
        });
        PTodo.add(BCanviarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });
        PTodo.add(BEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, -1));

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PTodo.add(BCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, -1));

        BCanviarInformacion.setText("Canviar Informacion");
        PTodo.add(BCanviarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, -1));

        BCargarDirecciones.setText("Cargar Direcciones");
        BCargarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BCargarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 140, -1));

        BGuardarDirecciones.setText("guardar Direcciones");
        BGuardarDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarDireccionesActionPerformed(evt);
            }
        });
        PTodo.add(BGuardarDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarList(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SeleccionarList
        seguridad();
    }//GEN-LAST:event_SeleccionarList

    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        ventana_Principal.addDireccion((java.io.File[]) getInformacionSelecionada());
        visualizarVentanPrincipal();
    }//GEN-LAST:event_BCargarActionPerformed

    private void BCanviarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCanviarNombreActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog("Escriba el nuevo nombre de la direccion");
        if (nuevoNombre != null && !nuevoNombre.isEmpty()) {
            try {
                A.canviarNombre((String) L.getSelectedValue(), nuevoNombre);
                actualizarLista();
                selecionarPrimero();
                A.guardarAdminastrador(direccionAdministrador);
            } catch (Exception ex) {
                responerException(ex);
            }
        }

    }//GEN-LAST:event_BCanviarNombreActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed

        try {
            A.eliminarInformacion(getNombreSelecionado());
            actualizarLista();
            selecionarPrimero();
            seguridad();
            A.guardarAdminastrador(direccionAdministrador);
        } catch (Exception ex) {
            responerException(ex);
        }

    }//GEN-LAST:event_BEliminarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        visualizarVentanPrincipal();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BCargarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarDireccionesActionPerformed
        //  JFileChooser jf = new JFileChooser();

        if (buscador(jf, this)) {
            try {
                A.addAdministrador((Admininistrador_De_Guardado<File[]>) Archivo.cargarArchivo(jf));
                A.guardarAdminastrador(direccionAdministrador);
                // A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(jf, new Administrador()));
                //   A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
                actualizarLista();
                selecionarPrimero();
                seguridad();
            } catch (Exception ex) {
                responerException(ex);
            }
        }
        //        A.addDirecciones((Administrador) cargarArchivoYCrearDeSerNesesario(new Administrador()));
        //        try {
        //            A.guardar(DIRECCION_ADMINISTRADOR_DIRECCIONES);
        //        } catch (Exception ex) {
        //            responerException(ex);
        //        }
        //        actualizarLista();
        //        selecionarPrimero();
        //        seguridad();
    }//GEN-LAST:event_BCargarDireccionesActionPerformed

    private void BGuardarDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarDireccionesActionPerformed
        try {
            //   crearArchivo(A);
            JFileChooser jf = new JFileChooser();

            if (buscador(jf, this)) {
                crearArchivo(jf, A);
            }
        } catch (Exception ex) {
            responerException(ex);
        }
    }//GEN-LAST:event_BGuardarDireccionesActionPerformed

    private void abrioVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_abrioVentana
        try {
            actualizar();
            selecionarPrimero();
            seguridad();
        } catch (Exception ex) {
            responerException(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_abrioVentana

    private void CerrarVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CerrarVentana
        cerrar(this);
    }//GEN-LAST:event_CerrarVentana
 public static void cerrar(JFrame f) {
        todo.Todo.cerrar(f,5);
    }
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        try {
            actualizar();
            selecionarPrimero();
            seguridad();
        } catch (Exception ex) {
            responerException(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ventana_Administrador_Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana_Administrador_Configuraciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BCanviarInformacion;
    private javax.swing.JButton BCanviarNombre;
    private javax.swing.JButton BCargar;
    private javax.swing.JButton BCargarDirecciones;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardarDirecciones;
    private javax.swing.JScrollPane JS;
    private javax.swing.JList L;
    private javax.swing.JPanel PTodo;
    // End of variables declaration//GEN-END:variables
}
