/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicaciones.calculadora_inteligente;

import Utiles.ClasesUtiles.Matematicas.*;
import Utiles.MetodosUtiles.Visual;
import static Utiles.MetodosUtiles.MetodosParaManipularMisClases.*;
import static Utiles.MetodosUtiles.MetodosUtiles.eliminarEspaciosDeStringLine;
import static Utiles.MetodosUtiles.Visual.maximizarVentana;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static todo.Todo.*;

/**
 * 5*9+(8^3)*2-sen(-8)
 *
 * @author Rene
 */
public class Calculadora_Inteligente extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora_Inteligente
     */
    public Calculadora_Inteligente() {
        initComponents();
        setLocation(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PTodo = new javax.swing.JPanel();
        TEntrada = new javax.swing.JTextField();
        TAnterior = new javax.swing.JTextField();
        BSen = new javax.swing.JButton();
        BCos = new javax.swing.JButton();
        BLn = new javax.swing.JButton();
        BTan = new javax.swing.JButton();
        BCsc = new javax.swing.JButton();
        BSec = new javax.swing.JButton();
        BCot1 = new javax.swing.JButton();
        BCopiar = new javax.swing.JButton();
        BPI = new javax.swing.JButton();
        BEuler = new javax.swing.JButton();
        BBackspace = new javax.swing.JButton();
        BLog = new javax.swing.JButton();
        BParentesisAbrir = new javax.swing.JButton();
        BParentesisCerrar = new javax.swing.JButton();
        BNumero = new javax.swing.JButton();
        BElevar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        BIgual = new javax.swing.JButton();
        BDividir = new javax.swing.JButton();
        BMenos = new javax.swing.JButton();
        BMultiplicar = new javax.swing.JButton();
        BPunto = new javax.swing.JButton();
        BNumero1 = new javax.swing.JButton();
        BNumero2 = new javax.swing.JButton();
        BNumero3 = new javax.swing.JButton();
        BNumero4 = new javax.swing.JButton();
        BNumero5 = new javax.swing.JButton();
        BNumero6 = new javax.swing.JButton();
        BNumero7 = new javax.swing.JButton();
        BNumero8 = new javax.swing.JButton();
        BNumero9 = new javax.swing.JButton();
        BMas = new javax.swing.JButton();
        BRaiz = new javax.swing.JButton();
        CSustituirConstantes = new javax.swing.JCheckBox();
        BAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerroVentana(evt);
            }
        });

        PTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TEntrada.setText("0");
        TEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EscribirEnEntrada(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DespuesDeEscribirEntrada(evt);
            }
        });
        PTodo.add(TEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, -1));

        TAnterior.setEditable(false);
        TAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAnterior.setText("0");
        TAnterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(TAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, -1));

        BSen.setText("Sen");
        BSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSenActionPerformed(evt);
            }
        });
        BSen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BSen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, -1));

        BCos.setText("Cos");
        BCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosActionPerformed(evt);
            }
        });
        BCos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        BLn.setText("Ln");
        BLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLnActionPerformed(evt);
            }
        });
        BLn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, -1));

        BTan.setText("Tan");
        BTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanActionPerformed(evt);
            }
        });
        BTan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        BCsc.setText("Csc");
        BCsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCscActionPerformed(evt);
            }
        });
        BCsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BCsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        BSec.setText("Sec");
        BSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSecActionPerformed(evt);
            }
        });
        BSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        BCot1.setText("Cot");
        BCot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCot1ActionPerformed(evt);
            }
        });
        BCot1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BCot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        BCopiar.setText("Copiar");
        BCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCopiarActionPerformed(evt);
            }
        });
        BCopiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

        BPI.setText("PI");
        BPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPIActionPerformed(evt);
            }
        });
        BPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, -1));

        BEuler.setText("E");
        BEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEulerActionPerformed(evt);
            }
        });
        BEuler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BEuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, -1));

        BBackspace.setText("←");
        BBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackspaceActionPerformed(evt);
            }
        });
        BBackspace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, -1));

        BLog.setText("Log");
        BLog.setToolTipText("Es de la forma log[ ]( ) dentro de los corchetes se pone la base y dentro de los  paréntesis el argumento  ");
        BLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogActionPerformed(evt);
            }
        });
        BLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        BParentesisAbrir.setText("(");
        BParentesisAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BParentesisAbrir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BParentesisAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 50, -1));

        BParentesisCerrar.setText(")");
        BParentesisCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BParentesisCerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BParentesisCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, -1));

        BNumero.setText("0");
        BNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, -1));

        BElevar.setText("^");
        BElevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BElevar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BElevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 50, -1));

        BBorrar.setText("C");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });
        BBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 50, -1));

        BIgual.setText("=");
        BIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIgualActionPerformed(evt);
            }
        });
        BIgual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 50, -1));

        BDividir.setText("/");
        BDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BDividir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 50, -1));

        BMenos.setText("-");
        BMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BMenos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 50, -1));

        BMultiplicar.setText("*");
        BMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BMultiplicar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, -1));

        BPunto.setText(".");
        BPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BPunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 50, -1));

        BNumero1.setText("1");
        BNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 50, -1));

        BNumero2.setText("2");
        BNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 50, -1));

        BNumero3.setText("3");
        BNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, -1));

        BNumero4.setText("4");
        BNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, -1));

        BNumero5.setText("5");
        BNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 50, -1));

        BNumero6.setText("6");
        BNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 50, -1));

        BNumero7.setText("7");
        BNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 50, -1));

        BNumero8.setText("8");
        BNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 50, -1));

        BNumero9.setText("9");
        BNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BNumero9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BNumero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 50, -1));

        BMas.setText("+");
        BMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApretarBotonCaracter(evt);
            }
        });
        BMas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(BMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 50, -1));

        BRaiz.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        BRaiz.setText("Raiz");
        BRaiz.setToolTipText("Es de la forma sqr[ ]( ) dentro de los corchetes se pone el índice y dentro de los  paréntesis el radical  ");
        BRaiz.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BRaiz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        BRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRaizActionPerformed(evt);
            }
        });
        PTodo.add(BRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 50, -1));

        CSustituirConstantes.setText("Sustituir Constates");
        CSustituirConstantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoltarTeclado(evt);
            }
        });
        PTodo.add(CSustituirConstantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        BAtras.setText("Atras");
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });
        PTodo.add(BAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jScrollPane1.setViewportView(PTodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEulerActionPerformed
        appendEntrada(TipoDeConstante.EULER.getCaracter());
    }//GEN-LAST:event_BEulerActionPerformed

    private void BPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPIActionPerformed
        appendEntrada(TipoDeConstante.PI.getCaracter());
    }//GEN-LAST:event_BPIActionPerformed

    private void ApretarBotonCaracter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApretarBotonCaracter
        appendEntrada(evt.getActionCommand());
    }//GEN-LAST:event_ApretarBotonCaracter

    private void BSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSenActionPerformed
        appendEntrada(TipoDeEnvoltura.SENO);
    }//GEN-LAST:event_BSenActionPerformed

    private void BCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCosActionPerformed
        appendEntrada(TipoDeEnvoltura.COSENO);
    }//GEN-LAST:event_BCosActionPerformed

    private void BRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRaizActionPerformed
        appendEntrada(TipoDeEnvoltura.RAIZ);
    }//GEN-LAST:event_BRaizActionPerformed

    private void BTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanActionPerformed
        appendEntrada(TipoDeEnvoltura.TANGENTE);
    }//GEN-LAST:event_BTanActionPerformed

    private void BCot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCot1ActionPerformed
        appendEntrada(TipoDeEnvoltura.COTAGENTE);
    }//GEN-LAST:event_BCot1ActionPerformed

    private void BSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSecActionPerformed
        appendEntrada(TipoDeEnvoltura.SECANTE);
    }//GEN-LAST:event_BSecActionPerformed

    private void BCscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCscActionPerformed
        appendEntrada(TipoDeEnvoltura.COSECANTE);
    }//GEN-LAST:event_BCscActionPerformed

    private void BLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLnActionPerformed
        appendEntrada(TipoDeEnvoltura.LOGARITMO_NAPERIANO);
    }//GEN-LAST:event_BLnActionPerformed

    private void BLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogActionPerformed
        appendEntrada(TipoDeEnvoltura.LOGARITMO);
    }//GEN-LAST:event_BLogActionPerformed

    private void BCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCopiarActionPerformed
        TEntrada.setText(TAnterior.getText());
        seguridadStringOperando(BIgual, TEntrada);
    }//GEN-LAST:event_BCopiarActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        TEntrada.setText("");
        Visual.establecerTextoPredeterminado("0", TEntrada);
        seguridadStringOperando(BIgual, TEntrada);
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackspaceActionPerformed
        //TEntrada.setText(TEntrada.getText().substring(0, TEntrada.getText().length() - 1));
        Backspace();
        // Visual.establecerTextoPredeterminado("0", TEntrada);
    }//GEN-LAST:event_BBackspaceActionPerformed

    private void DespuesDeEscribirEntrada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DespuesDeEscribirEntrada
        //Visual.establecerTextoPredeterminado("0", TEntrada);
        //  SoltarTeclado(evt);
        despuesDeEscribir(evt, true);
    }//GEN-LAST:event_DespuesDeEscribirEntrada

    private void EscribirEnEntrada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EscribirEnEntrada
        Visual.eliminarTextoPredeterminado("0", TEntrada);
        //  SoltarTeclado(evt);
        //despuesDeEscribir(evt, true);
    }//GEN-LAST:event_EscribirEnEntrada

    private void BIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIgualActionPerformed
        responder();
    }//GEN-LAST:event_BIgualActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void SoltarTeclado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoltarTeclado
        despuesDeEscribir(evt, false);
    }//GEN-LAST:event_SoltarTeclado

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        maximizarVentana(ventanaTodo);
        setVisible(false);
    }//GEN-LAST:event_BAtrasActionPerformed

    private void cerroVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerroVentana
        alCerrar(this);
    }//GEN-LAST:event_cerroVentana

    public void alCerrar(JFrame f) {
        cerrar(f, 3);
    }

    private void appendEntrada(TipoDeEnvoltura a) {
        appendEntrada(a.getInicio() + a.getMedio() + a.getFin());
    }

    private void appendEntrada(char a) {
        appendEntrada(a + "");
    }

    private void appendEntrada(String a) {
        Visual.eliminarTextoPredeterminado("0", TEntrada);
        TEntrada.setText(TEntrada.getText() + a);
        seguridadStringOperando(BIgual, TEntrada);
    }

    private void responder() {
        try {
//            TEntrada.setText(eliminarEspaciosDeStringLine(TEntrada.getText()));
//            if(!comprobarStringOperando(TEntrada.getText())){
//            throw new Exception();
//            }
            Operando respuesta = interpreteStringSimplificado(TEntrada.getText());
            TAnterior.setText(TEntrada.getText());
            TEntrada.setText(CSustituirConstantes.isSelected() ? sustituirConstantes(respuesta).toString() : respuesta.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Se equivocó en la entrada de datos por favor rectifique", "Rectificación", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void despuesDeEscribir(java.awt.event.KeyEvent evt, boolean realizoEfecto) {

        //seguridadStringOperando(BIgual, TEntrada);
        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_ENTER:
                if (BIgual.isEnabled()) {
                    responder();
                }
                break;
            case java.awt.event.KeyEvent.VK_BACK_SPACE:
                if (!realizoEfecto) {
                    Backspace();
                    return;
                }
                break;
        }
        Visual.establecerTextoPredeterminado("0", TEntrada);
        seguridadStringOperando(BIgual, TEntrada);
    }

    private void Backspace() {
        TEntrada.setText(TEntrada.getText().substring(0, TEntrada.getText().length() - 1));
        Visual.establecerTextoPredeterminado("0", TEntrada);
        seguridadStringOperando(BIgual, TEntrada);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Inteligente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Inteligente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Inteligente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Inteligente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_Inteligente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BBackspace;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BCopiar;
    private javax.swing.JButton BCos;
    private javax.swing.JButton BCot1;
    private javax.swing.JButton BCsc;
    private javax.swing.JButton BDividir;
    private javax.swing.JButton BElevar;
    private javax.swing.JButton BEuler;
    private javax.swing.JButton BIgual;
    private javax.swing.JButton BLn;
    private javax.swing.JButton BLog;
    private javax.swing.JButton BMas;
    private javax.swing.JButton BMenos;
    private javax.swing.JButton BMultiplicar;
    private javax.swing.JButton BNumero;
    private javax.swing.JButton BNumero1;
    private javax.swing.JButton BNumero2;
    private javax.swing.JButton BNumero3;
    private javax.swing.JButton BNumero4;
    private javax.swing.JButton BNumero5;
    private javax.swing.JButton BNumero6;
    private javax.swing.JButton BNumero7;
    private javax.swing.JButton BNumero8;
    private javax.swing.JButton BNumero9;
    private javax.swing.JButton BPI;
    private javax.swing.JButton BParentesisAbrir;
    private javax.swing.JButton BParentesisCerrar;
    private javax.swing.JButton BPunto;
    private javax.swing.JButton BRaiz;
    private javax.swing.JButton BSec;
    private javax.swing.JButton BSen;
    private javax.swing.JButton BTan;
    private javax.swing.JCheckBox CSustituirConstantes;
    private javax.swing.JPanel PTodo;
    private javax.swing.JTextField TAnterior;
    private javax.swing.JTextField TEntrada;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
